document.addEventListener("DOMContentLoaded",()=>{const $=(s,p=document)=>p.querySelector(s),$$=(s,p=document)=>[...p.querySelectorAll(s)];
setTimeout(()=>$("#loader")?.classList.add("hide"),1100);$("#year").textContent=new Date().getFullYear();
const title=$("#heroTitle");if(title){let out="",d=0,inside=false,tag="";for(const c of title.innerHTML){if(c==="<"){inside=true;tag=c;continue}if(inside){tag+=c;if(c===">"){inside=false;out+=tag}continue}if(c===" ")out+='<span class="space">&nbsp;</span>';else if(c==="\n")out+=c;else{out+=`<span class="char" style="animation-delay:${d}s">${c}</span>`;d+=.035}}title.innerHTML=out}
const menu=$("#menu"),nav=$("#nav");menu?.addEventListener("click",()=>{const open=nav.classList.toggle("open");menu.classList.toggle("open",open)});$$("nav a").forEach(a=>a.addEventListener("click",()=>{nav.classList.remove("open");menu.classList.remove("open")}));
const progress=$("#progress"),top=$("#top"),header=$(".header");function ui(){const y=scrollY,total=document.documentElement.scrollHeight-innerHeight;progress.style.width=(total?y/total*100:0)+"%";header.classList.toggle("scrolled",y>30);top.classList.toggle("show",y>600)}addEventListener("scroll",ui,{passive:true});ui();top?.addEventListener("click",()=>scrollTo({top:0,behavior:"smooth"}));
const items=$$(".reveal,.reveal-scale");if("IntersectionObserver"in window){const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add("visible");io.unobserve(e.target)}}),{threshold:.1});items.forEach(x=>io.observe(x))}else items.forEach(x=>x.classList.add("visible"));
const filters=$$(".filters button"),cards=$$(".service");filters.forEach(btn=>btn.addEventListener("click",()=>{filters.forEach(x=>x.classList.remove("active"));btn.classList.add("active");const f=btn.dataset.filter;cards.forEach(c=>c.style.display=f==="all"||c.dataset.cat===f?"flex":"none")}));
$$(".book").forEach(btn=>btn.addEventListener("click",()=>{const msg=`Hola Angiie, me interesa agendar ${btn.dataset.service}. ¿Qué horarios tienes disponibles?`;open("https://wa.me/529681093076?text="+encodeURIComponent(msg),"_blank")}));
$$(".faq").forEach(x=>x.addEventListener("click",()=>x.classList.toggle("open")));
$("#copyPhone")?.addEventListener("click",async()=>{try{await navigator.clipboard.writeText("9681093076");$("#copyPhone").textContent="¡Copiado!";setTimeout(()=>$("#copyPhone").textContent="Copiar teléfono",1800)}catch{alert("Teléfono: 968 109 3076")}});
const modal=$("#modal"),content=$("#modalContent");$$(".gallery-item").forEach(item=>item.addEventListener("click",()=>{const src=item.dataset.image;content.innerHTML=`<img src="${src}" alt="Trabajo de Angiie Valdez" onerror="this.remove();this.parentElement.innerHTML='<b>Tu foto aquí</b><small>Coloca la imagen como ${src}</small>'">`;modal.classList.add("open");document.body.classList.add("lock")}));function close(){modal.classList.remove("open");document.body.classList.remove("lock")}$("#closeModal")?.addEventListener("click",close);modal?.addEventListener("click",e=>{if(e.target===modal)close()});addEventListener("keydown",e=>{if(e.key==="Escape")close()});
const status=$("#statusText"),pill=$(".status");if(status){const d=new Date(),day=d.getDay(),m=d.getHours()*60+d.getMinutes();let openNow=day>=1&&day<=5?m>=540&&m<1140:day===6?m>=600&&m<840:false;status.textContent=openNow?"Abierto ahora · Por cita":"Horario cerrado · Agenda tu cita";if(openNow)pill.classList.add("open")}
$$('a[href^="#"]').forEach(a=>a.addEventListener("click",e=>{const el=$(a.getAttribute("href"));if(el){e.preventDefault();el.scrollIntoView({behavior:"smooth"})}}));});